# Generated by Django 5.1.4 on 2025-02-27 16:59

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'ordering': ['-created_on'],
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='email_idx',
            old_name='users_user_email_6f2530_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='mobile_idx',
            old_name='users_user_mobile_7d27b4_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='account_verified',
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user's account has been verified",
                verbose_name='Account verified',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP address of the user's last login",
                null=True,
                verbose_name='Last login IP',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(
                blank=True,
                help_text='Country code for mobile number (e.g., +1, +91)',
                max_length=10,
                null=True,
                verbose_name='Country code',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='cr_by_self',
            field=models.BooleanField(
                default=False,
                help_text='Indicates if the user created their own account',
                verbose_name='Self-created account',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True,
                help_text="User's first name",
                max_length=128,
                null=True,
                verbose_name='First name',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('M', 'Male'),
                    ('F', 'Female'),
                    ('O', 'Other'),
                    ('P', 'Prefer not to say'),
                ],
                help_text="User's gender",
                max_length=1,
                null=True,
                verbose_name='Gender',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_password_reset_link_sent',
            field=models.BooleanField(
                default=False,
                help_text='Flag indicating if a password reset link has been sent',
                verbose_name='Password reset link sent',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user is a seller',
                verbose_name='Seller status',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user has super admin privileges',
                verbose_name='Super admin status',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True,
                help_text="User's last name",
                max_length=128,
                null=True,
                verbose_name='Last name',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(
                blank=True,
                help_text='Primary mobile number used for authentication',
                max_length=20,
                null=True,
                unique=True,
                validators=[utils.validators.validate_phone_number],
                verbose_name='Mobile number',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(
                blank=True,
                help_text="User's profile picture",
                null=True,
                upload_to='profile_pics/%Y/%m/',
                verbose_name='Profile picture',
            ),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_on'], name='user_created_idx'),
        ),
    ]
