# Generated by Django 5.1.4 on 2025-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'identifier',
                    models.CharField(
                        help_text='Phone number or email for which OTP is generated',
                        max_length=100,
                        verbose_name='Identifier',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('PHONE', 'Phone'), ('EMAIL', 'Email')],
                        help_text='Whether OTP is sent to phone or email',
                        max_length=10,
                        verbose_name='OTP Type',
                    ),
                ),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('REGISTER', 'Registration'),
                            ('LOGIN', 'Login'),
                            ('RESET_PASSWORD', 'Reset Password'),
                            ('VERIFY_NEW_PHONE', 'Verify New Phone'),
                        ],
                        help_text='Purpose for which OTP is generated',
                        max_length=20,
                        verbose_name='OTP Purpose',
                    ),
                ),
                (
                    'otp',
                    models.CharField(
                        help_text='Generated OTP code',
                        max_length=6,
                        verbose_name='OTP Code',
                    ),
                ),
                (
                    'is_verified',
                    models.BooleanField(
                        default=False,
                        help_text='Whether the OTP has been verified',
                        verbose_name='Is Verified',
                    ),
                ),
                (
                    'attempts',
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text='Number of verification attempts',
                        verbose_name='Verification Attempts',
                    ),
                ),
                (
                    'max_attempts',
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text='Maximum allowed verification attempts',
                        verbose_name='Max Attempts',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='When the OTP was generated',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        help_text='When the OTP expires',
                        verbose_name='Expires At',
                    ),
                ),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'indexes': [
                    models.Index(
                        fields=['identifier'], name='otp_identifier_idx'
                    ),
                    models.Index(fields=['created_at'], name='otp_created_idx'),
                ],
            },
        ),
    ]
