# Generated by Django 5.1.4 on 2025-03-01 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('google', 'Google'),
                            ('facebook', 'Facebook'),
                            ('apple', 'Apple'),
                        ],
                        help_text='Social authentication provider (e.g., Google, Facebook)',
                        max_length=20,
                        verbose_name='Provider',
                    ),
                ),
                (
                    'provider_id',
                    models.CharField(
                        help_text='Unique ID from the social provider',
                        max_length=255,
                        verbose_name='Provider ID',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        help_text='Email address from the social provider',
                        max_length=254,
                        null=True,
                        verbose_name='Provider Email',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True,
                        help_text="User's name from the social provider",
                        max_length=255,
                        null=True,
                        verbose_name='Provider Name',
                    ),
                ),
                (
                    'profile_picture',
                    models.URLField(
                        blank=True,
                        help_text='Profile picture URL from the social provider',
                        null=True,
                        verbose_name='Profile Picture URL',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='User this social account belongs to',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='social_accounts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'unique_together': {('provider', 'provider_id')},
            },
        ),
    ]
