# Generated by Django 5.1.4 on 2025-03-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_seller_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='sellerverificationfile',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sellerverificationfile',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='sellerverificationfile',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='sellerverificationfile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sellerverificationfile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_by',
        ),
    ]
