[tool.black]
line-length = 80
skip-string-normalization = true
include = '\.pyi?$'
extend-exclude = '''
^/migrations/
'''

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = ["E", "F", "D", "W"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200", "D205", "D400", "D401", "D415"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[tool.isort]
profile = "black"
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["migrations"]
