# Generated by Django 5.1.4 on 2025-02-27 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={
                'ordering': ['display_order', '-created_on'],
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='display_order',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Controls the order in which banners are displayed             (lower numbers shown first).',
                verbose_name='Display Order',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(
                help_text='Banner image (recommended size: 1200x500px).',
                upload_to='banners/%Y/%m/',
                verbose_name='Banner Image',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Controls whether this banner is currently displayed on             the site.',
                verbose_name='Active Status',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(
                blank=True,
                help_text='Short subtitle or descriptive text displayed below the             title.',
                max_length=255,
                null=True,
                verbose_name='Subtitle',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='Main title displayed on the banner.',
                max_length=255,
                null=True,
                verbose_name='Title',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(
                blank=True,
                default='/shop-grid-standard',
                help_text='URL where the banner redirects when clicked.',
                max_length=255,
                null=True,
                verbose_name='Redirect URL',
            ),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['is_active'], name='banner_active_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(
                fields=['display_order'], name='banner_order_idx'
            ),
        ),
    ]
