# Generated by Django 5.1.4 on 2025-03-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_banner_options_banner_display_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={
                'ordering': ['display_order', '-created_at'],
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated_by',
        ),
    ]
