# Generated by Django 5.1.4 on 2025-03-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_listingimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='deleted_on',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_by',
        ),
    ]
