# Generated by Django 5.1.4 on 2025-03-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'listings',
            '0004_comment_joblisting_propertylisting_searchquery_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
