# Generated by Django 5.1.4 on 2025-02-27 07:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text='Designates whether this record is active. Default is True.',
                    ),
                ),
                (
                    'is_deleted',
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text='Designates whether this record was deleted using soft             deletion. Default is False.',
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text='Timestamp when this record was created.',
                    ),
                ),
                (
                    'updated_on',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='Timestamp when this record was last updated.',
                    ),
                ),
                (
                    'deleted_on',
                    models.DateTimeField(
                        blank=True,
                        help_text='Timestamp when this record was soft deleted.',
                        null=True,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of the category (e.g., Electronics, Clothing, Books).',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        help_text='SEO-friendly slug (auto-generated if left blank).',
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        help_text='Optional image representing the category.',
                        null=True,
                        upload_to='category_images',
                    ),
                ),
                (
                    'keyword',
                    models.CharField(
                        blank=True,
                        help_text='SEO keywords for the category (comma-separated).',
                        max_length=350,
                        null=True,
                    ),
                ),
                (
                    'meta_name',
                    models.CharField(
                        blank=True,
                        help_text='SEO meta title for search engine visibility.',
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    'meta_description',
                    models.CharField(
                        blank=True,
                        help_text='SEO meta description to improve search ranking.',
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    'is_featured',
                    models.BooleanField(
                        default=False,
                        help_text='Check if this category should be featured.',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_created',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent category (if this is a sub-category).',
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='subcategories',
                        to='shop.category',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(class)s_updated',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
    ]
