# Generated by Django 5.1.4 on 2025-02-27 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={
                'ordering': ['display_order', 'name'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Controls the display order (lower numbers first).',
                verbose_name='Display Order',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Optional image representing the category.',
                null=True,
                upload_to='categories/%Y/%m/',
                verbose_name='Category Image',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Whether this category is active and visible.',
                verbose_name='Active',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(
                default=False,
                help_text='Check if this category should be featured.',
                verbose_name='Featured',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='keyword',
            field=models.CharField(
                blank=True,
                help_text='SEO keywords for the category (comma-separated).',
                max_length=350,
                null=True,
                verbose_name='SEO Keywords',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(
                blank=True,
                help_text='SEO meta description to improve search ranking.',
                max_length=500,
                null=True,
                verbose_name='Meta Description',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_name',
            field=models.CharField(
                blank=True,
                help_text='SEO meta title for search engine visibility.',
                max_length=250,
                null=True,
                verbose_name='Meta Title',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                help_text='Name of the category (e.g., Electronics, Clothing).',
                max_length=100,
                unique=True,
                verbose_name='Category Name',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                help_text='Parent category (if this is a sub-category).',
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name='subcategories',
                to='shop.category',
                verbose_name='Parent Category',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='SEO-friendly URL slug (auto-generated if blank).',
                max_length=120,
                null=True,
                unique=True,
                verbose_name='URL Slug',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text='Whether this tag is active and visible to users.',
                verbose_name='Active',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                help_text='Tag name (e.g., Sale, New Arrival, Eco-friendly).',
                max_length=100,
                unique=True,
                verbose_name='Tag Name',
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='SEO-friendly URL slug (auto-generated if blank).',
                max_length=120,
                null=True,
                unique=True,
                verbose_name='URL Slug',
            ),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='category_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(
                fields=['is_active'], name='category_active_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(
                fields=['is_featured'], name='category_featured_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='category_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tag_name_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tag_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active'], name='tag_active_idx'),
        ),
    ]
